CREATE DATABASE QUANLYNHAHANG;
GO

CREATE TABLE RESTAURANTS (
	ID INT IDENTITY(1, 1),
	NAME NVARCHAR(255) NOT NULL,
	ADDRESS NVARCHAR(255),
	TIMEZONE VARCHAR(50) NULL,
	CONFIG NVARCHAR(MAX),	--JSON
	CREATED_AT DATETIME DEFAULT GETDATE(),
	UPDATED_AT DATETIME,
	CONSTRAINT PK_RESTAURANTS PRIMARY KEY (ID)
);
GO

INSERT INTO RESTAURANTS (NAME, ADDRESS, TIMEZONE)
VALUES (N'Cơm Quê Dượng Bầu', N'Chung cư, 40E Ngô Đức Kế, Bến Nghé, Quận 1, Thành phố Hồ Chí Minh 75000', 'Asia/Ho_Chi_Minh');
GO

--UPDATE THU CONG
--UPDATE RESTAURANTS
--SET NAME = N'NEW NAME';
--	UPDATED_AT = GETDATE()
--WHERE ID = 1;

--SU DUNG TRIGGER
CREATE TRIGGER TRG_RESTAURANTS_UPDATE_TIMESTAMP
ON RESTAURANTS
AFTER UPDATE
AS
BEGIN
	UPDATE R
	SET UPDATED_AT = GETDATE()
	FROM RESTAURANTS R
	INNER JOIN INSERTED I ON R.ID = I.ID;
END;
GO

CREATE TABLE TABLES (
	ID INT IDENTITY(1, 1),
	RESTAURANT_ID INT NOT NULL,
	CODE VARCHAR(50) NOT NULL,
	NAME NVARCHAR(100),
	SEATS INT DEFAULT 4,
	AREA NVARCHAR(50),
	IS_ACTIVE BIT DEFAULT 1,
	CREATED_AT DATETIME DEFAULT GETDATE(),
	UPDATED_AT DATETIME,
	CONSTRAINT PK_TABLES PRIMARY KEY (ID),
	CONSTRAINT FK_TABLES_RESTAURANT FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (ID),
	CONSTRAINT UQ_TABLES_RESTAURANTCODE UNIQUE (RESTAURANT_ID, CODE)
);
GO

INSERT INTO TABLES (RESTAURANT_ID, CODE, NAME, SEATS)
VALUES
(1, 'A1', N'Bàn 01 - Khu A', 4),
(1, 'A2', N'Bàn 02 - Khu A', 6),
(1, 'B1', N'Bàn 01 - Khu B', 8),
(1, 'B2', N'Bàn 02 - Khu B', 4),
(1, 'C1', N'Bàn 01 - Khu C', 6),
(1, 'C2', N'Bàn 02 - Khu C', 8);
GO

CREATE TRIGGER TRG_TABLES_UPDATE_TIEMSTAMP
ON TABLES
AFTER UPDATE
AS
BEGIN
	UPDATE T
	SET UPDATED_AT = GETDATE()
	FROM TABLES T
	INNER JOIN INSERTED I ON T.ID = I.ID;
END;
GO

CREATE TABLE QRTOKENS (
	ID INT IDENTITY(1, 1),
	TABLE_ID INT NOT NULL,
	TOKEN VARCHAR(255) NOT NULL,
	URL VARCHAR(500),
	EXPIRES_AT DATETIME NULL,
	CREATED_AT DATETIME DEFAULT GETDATE(),
	UPDATED_AT DATETIME,
	CONSTRAINT PK_QRTOKENS PRIMARY KEY (ID),
	CONSTRAINT FK_QRTOKENS_TABLE FOREIGN KEY (TABLE_ID) REFERENCES TABLES (ID),
	CONSTRAINT UQ_QRTOKENS_TOKEN UNIQUE (TOKEN)
);
GO

--Lấy IDs của các bàn vừa tạo (Dùng cho QRTokens)
DECLARE @TABLEID_A1 INT = (SELECT ID FROM TABLES WHERE CODE = 'A1' AND RESTAURANT_ID = 1);
DECLARE @TABLEID_A2 INT = (SELECT ID FROM TABLES WHERE CODE = 'A2' AND RESTAURANT_ID = 1);
DECLARE @TABLEID_B1 INT = (SELECT ID FROM TABLES WHERE CODE = 'B1' AND RESTAURANT_ID = 1);
DECLARE @TABLEID_B2 INT = (SELECT ID FROM TABLES WHERE CODE = 'B2' AND RESTAURANT_ID = 1);
DECLARE @TABLEID_C1 INT = (SELECT ID FROM TABLES WHERE CODE = 'C1' AND RESTAURANT_ID = 1);
DECLARE @TABLEID_C2 INT = (SELECT ID FROM TABLES WHERE CODE = 'C2' AND RESTAURANT_ID = 1);
/*False*/

INSERT INTO QRTOKENS (TABLE_ID, TOKEN)
VALUES
(@TABLEID_A1, 'A1-abcdxyz'),
(@TABLEID_A2, 'A2-abcdxyt'),
(@TABLEID_B1, 'B1-abcd1234'),
(@TABLEID_B2, 'B2-abcd5678'),
(@TABLEID_C1, 'C1-xyz1234'),
(@TABLEID_C2, 'C2-xyz5678');
GO

CREATE TRIGGER TRG_QRTOKENS_UPDATE_TIMESTAMP
ON QRTOKENS
AFTER UPDATE
AS
BEGIN
	UPDATE Q
	SET UPDATED_AT = GETDATE()
	FROM QRTOKENS Q
	INNER JOIN INSERTED I ON Q.ID = I.ID;
END;
GO

CREATE TABLE CATEGORIES (
	ID INT IDENTITY(1, 1),
	RESTAURANT_ID INT NOT NULL,
	NAME NVARCHAR(100) NOT NULL,
	ORDER_INDEX INT DEFAULT 0,
	CREATED_AT DATETIME DEFAULT GETDATE(),
	UPDATED_AT DATETIME,
	CONSTRAINT PK_CATEGORIES PRIMARY KEY (ID),
	CONSTRAINT FK_CATEGORIES_RESTAURANT FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (ID)
);
GO

INSERT INTO CATEGORIES (RESTAURANT_ID, NAME) VALUES (1, N'Đồ uống'), (1, N'Món chính'), (1, N'Tráng miệng');
GO

CREATE TRIGGER TRG_CATEGORIES_UPDATE_TIMESTAMP
ON CATEGORIES
AFTER UPDATE
AS
BEGIN
	UPDATE C
	SET UPDATED_AT = GETDATE()
	FROM CATEGORIES C
	INNER JOIN INSERTED I ON C.ID = I.ID;
END;
GO

CREATE TABLE STATIONS (
	ID INT IDENTITY(1, 1),
	RESTAURANT_ID INT NOT NULL,
	CODE VARCHAR(50) NOT NULL,
	NAME NVARCHAR(100) NOT NULL,
	PRIORIRY INT DEFAULT 0,
	IS_ACTIVE BIT DEFAULT 1,
	CREATED_AT DATETIME DEFAULT GETDATE(),
	UPDATED_AT DATETIME,
	CONSTRAINT PK_STATIONS PRIMARY KEY (ID),
	CONSTRAINT FK_STATIONS_RESTAURANT FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (ID),
	CONSTRAINT UQ_STATIONS_RESTAURANTCODE UNIQUE (RESTAURANT_ID, CODE)
);
GO

INSERT INTO STATIONS (RESTAURANT_ID, CODE, NAME) VALUES (1, 'bar', N'Quầy pha chế'), (1, 'hot', N'Bếp nóng'), (1, 'cold', N'Bếp lạnh');
GO

CREATE TRIGGER TRG_STATIONS_UPDATE_TIMESTAMP
ON STATIONS
AFTER UPDATE
AS
BEGIN
	UPDATE S
	SET UPDATED_AT = GETDATE()
	FROM STATIONS S
	INNER JOIN INSERTED I ON S.ID = I.ID;
END;
GO

CREATE TABLE MENUITEMS (
	ID INT IDENTITY(1, 1),
	RESTAURANT_ID INT NOT NULL,
	CATEGORY_ID INT NOT NULL,
	STATION_ID INT,
	NAME NVARCHAR(255) NOT NULL,
	DESCRIPTION NVARCHAR(500),
	PRICE MONEY NOT NULL,
	IS_AVAILABLE BIT DEFAULT 1,
	ETA_MIN SMALLINT,
	ETA_MAX SMALLINT,
	TAGS NVARCHAR(MAX),
	IMAGE_URL VARCHAR(500),
	CREATED_AT DATETIME DEFAULT GETDATE(),
	UPDATED_AT DATETIME,
	CONSTRAINT PK_MENUITEMS PRIMARY KEY (ID),
	CONSTRAINT FK_MENUITEMS_RESTAURANT FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (ID),
	CONSTRAINT FK_MENUITEMS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID),
	CONSTRAINT FK_MENUITEMS_STATION FOREIGN KEY (STATION_ID) REFERENCES STATIONS (ID)
);
GO

DECLARE @CATID_DRINK INT = (SELECT ID FROM CATEGORIES WHERE NAME = N'Đồ uống');
DECLARE @CATID_MAIN INT = (SELECT ID FROM CATEGORIES WHERE NAME = N'Món chính');
DECLARE @CATID_DESSERT INT = (SELECT ID FROM CATEGORIES WHERE NAME = N'Tráng miệng');
DECLARE @STATID_BAR INT = (SELECT ID FROM STATIONS WHERE CODE = 'bar');
DECLARE @STATID_HOT INT = (SELECT ID FROM STATIONS WHERE CODE = 'hot');
DECLARE @STATID_COLD INT = (SELECT ID FROM STATIONS WHERE CODE = 'cold');

/*False*/
INSERT INTO MENUITEMS (RESTAURANT_ID, CATEGORY_ID, STATION_ID, NAME, PRICE, ETA_MIN, ETA_MAX)
VALUES
(1, @CATID_DRINK, @STATID_BAR, N'Nước suối', 25000, 2, 5),
(1, @CATID_DRINK, @STATID_BAR, N'Coca cola', 30000, 2, 5),
(1, @CATID_MAIN, @STATID_HOT, N'Ba rọi cháy cạnh', 125000, 10, 15),
(1, @CATID_MAIN, @STATID_HOT, N'Tôm rim thịt', 125000, 10, 15),
(1, @CATID_MAIN, @STATID_HOT, N'Gà sả ớt', 125000, 15, 20),
(1, @CATID_MAIN, @STATID_HOT, N'Thịt kho tiêu', 125000, 20, 25),
(1, @CATID_DESSERT, @STATID_COLD, N'Sương sa hạt lựu', 55000, 10, 12),
(1, @CATID_DESSERT, @STATID_COLD, N'Chè đậu xanh đánh', 55000, 10, 12);
GO

CREATE TRIGGER TRG_MENUITEMS_UPDATE_TIMESTAMP
ON MENUITEMS
AFTER UPDATE
AS
BEGIN
	UPDATE M
	SET UPDATED_AT = GETDATE()
	FROM MENUITEMS M
	INNER JOIN INSERTED I ON M.ID = I.ID;
END;
GO

CREATE TABLE MENUITEMVARIANTS (
	ID INT IDENTITY(1, 1),
	MENUITEM_ID INT NOT NULL,
	NAME NVARCHAR(100) NOT NULL,
	EXTRA_PRICE DECIMAL(10, 2) DEFAULT 0,
	IS_AVAILABLE BIT DEFAULT 1,
	CREATED_AT DATETIME DEFAULT GETDATE(),
	UPDATED_AT DATETIME,
	CONSTRAINT PK_MENUITEMVARIANTS PRIMARY KEY (ID),
	CONSTRAINT FK_MENUITEMVARIANTS_MENUITEM FOREIGN KEY (MENUITEM_ID) REFERENCES MENUITEMS (ID)
);
GO

CREATE TRIGGER TRG_MENUITEMVARIANTS_UPDATE_TIMESTAMP
ON MENUITEMVARIANTS
AFTER UPDATE
AS
BEGIN
	UPDATE V
	SET UPDATED_AT = GETDATE()
	FROM MENUITEMVARIANTS V
	INNER JOIN INSERTED I ON V.ID = I.ID;
END;
GO

CREATE TABLE ORDERS (
	ID INT IDENTITY(1, 1),
	RESTAURANT_ID INT NOT NULL,
	TABLE_ID INT NOT NULL,
	ORDER_TOKEN VARCHAR(255),
	--0 = Pending, 1 = Accepted, 2 = Preparing, 3 = Served, 4 = Closed, 5 = Cancelled
	STATUS TINYINT NOT NULL DEFAULT 0,
	TOTAL DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
	GUEST_NOTE NVARCHAR(500) NULL,
	--0 = Unpaid, 1 = Paid, 2 = Refunded
	PAYMENT_STATUS TINYINT NOT NULL DEFAULT 0,
	CREATED_BY INT NULL,
	CREATED_AT DATETIME DEFAULT GETDATE(),
	CLOSED_AT DATETIME NULL,
	UPDATED_AT DATETIME,
	CONSTRAINT PK_ORDERS PRIMARY KEY (ID),
	CONSTRAINT FK_ORDERS_RESTAURANT FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (ID),
	CONSTRAINT FK_ORDERS_TABLE FOREIGN KEY (TABLE_ID) REFERENCES TABLES (ID),
	--CONSTRAINT FK_ORDERS_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES USERS (ID),
	CONSTRAINT UQ_ORDERS_ORDER_TOKEN UNIQUE (ORDER_TOKEN)
);
GO

CREATE TRIGGER TRG_ORDERS_UPDATE_TIMESTAMP
ON ORDERS
AFTER UPDATE
AS
BEGIN
	UPDATE O
	SET UPDATED_AT = GETDATE()
	FROM ORDERS O
	INNER JOIN INSERTED I ON O.ID = I.ID;
END;
GO

CREATE TABLE ORDERITEMS (
	ID INT IDENTITY(1, 1),
	ORDER_ID INT NOT NULL,
	MENUITEM_ID INT NOT NULL,
	MENUITEMVARIANT_ID INT NULL,
	QUANTITY SMALLINT NOT NULL DEFAULT 1,
	UNIT_PRICE DECIMAL(10, 2) NOT NULL,
	LINE_TOTAL DECIMAL(10, 2) NOT NULL,
	NOTE NVARCHAR(255) NULL,
	--0 = Pending, 1 = Preparing, 2 = Ready, 3 = Served, 4 = Cancelled
	STATUS TINYINT NOT NULL DEFAULT 0,
	ASSIGNED_TO INT NULL,
	STARTED_AT DATETIME NULL,
	FINISHED_AT DATETIME NULL,
	CREATED_AT DATETIME DEFAULT GETDATE(),
	UPDATED_AT DATETIME,
	CONSTRAINT PK_ORDERITEMS PRIMARY KEY (ID),
	CONSTRAINT FK_ORDERITEMS_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID),
	CONSTRAINT FK_ORDERITEMS_MENUITEM FOREIGN KEY (MENUITEM_ID) REFERENCES MENUITEMS (ID),
	CONSTRAINT FK_ORDERITEMS_MENUITEMVARIANT FOREIGN KEY (MENUITEMVARIANT_ID) REFERENCES MENUITEMVARIANTS (ID)
);
GO

CREATE TRIGGER TRG_ORDERITEMS_UPDATE_TIMESTAMP
ON ORDERITEMS
AFTER UPDATE
AS
BEGIN
	UPDATE O
	SET UPDATED_AT = GETDATE()
	FROM ORDERITEMS O
	INNER JOIN INSERTED I ON O.ID = I.ID;
END;
GO

CREATE TABLE ROLES (
	ID INT IDENTITY(1, 1),
	NAME VARCHAR(50) NOT NULL,
	PERMISSIONS NVARCHAR(MAX) NULL,
	CREATED_AT DATETIME DEFAULT GETDATE(),
	UPDATED_AT DATETIME,
	CONSTRAINT PK_ROLES PRIMARY KEY (ID),
	CONSTRAINT UQ_ROLES_NAME UNIQUE (NAME)
);
GO

INSERT INTO ROLES (NAME) VALUES ('Admin'), ('Kitchen'), ('Waiter');
GO

CREATE TRIGGER TRG_ROLES_UPDATE_TIMESTAMP
ON ROLES
AFTER UPDATE
AS
BEGIN
	UPDATE R
	SET UPDATED_AT = GETDATE()
	FROM ROLES R
	INNER JOIN INSERTED I ON R.ID = I.ID;
END;
GO

CREATE TABLE USERS (
	ID INT IDENTITY(1, 1),
	USERNAME VARCHAR(100) NOT NULL,
	FULL_NAME NVARCHAR(255),
	PASSWORD_HASH VARCHAR(255) NULL,
	ROLE_ID INT NOT NULL,
	RESTAURANT_ID INT NOT NULL,
	IS_ACTIVE BIT DEFAULT 1,
	LAST_LOGIN_AT DATETIME NULL,
	CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME,
	CONSTRAINT PK_USERS PRIMARY KEY (ID),
	CONSTRAINT FK_USERS_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID),
	CONSTRAINT FK_USERS_RESTAURANT FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (ID),
	CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME)
);
GO

INSERT INTO USERS (USERNAME, FULL_NAME, ROLE_ID, RESTAURANT_ID)
VALUES
('admin@123', N'Nguyễn Hải Yến', 1, 1),
('chef@123', N'Lê Nhật Long', 2, 1),
('waitress@123', N'Nguyễn Diệu Linh', 3, 1),
('waiter@123', N'Lưu Minh Thắng', 3, 1);
GO

CREATE TRIGGER TRG_USERS_UPDATE_TIMESTAMP
ON USERS
AFTER UPDATE
AS
BEGIN
	UPDATE U
	SET UPDATED_AT = GETDATE()
	FROM USERS U
	INNER JOIN INSERTED I ON U.ID = I.ID;
END;
GO

CREATE TABLE PAYMENTS (
	ID INT IDENTITY(1, 1),
	ORDER_ID INT NOT NULL,
	AMOUNT DECIMAL(18, 2) NOT NULL,
	METHOD VARCHAR(50) NOT NULL,
	PROVIDER VARCHAR(50) NULL,
	PROVIDER_REF VARCHAR(255) NULL,
	--0 = initiated, 1 = success, 2 = failed, 3 = cancelled
	STATUS TINYINT NOT NULL DEFAULT 0,
	REQUEST_PAYLOAD NVARCHAR(MAX) NULL,
	RESPONSE_PAYLOAD NVARCHAR(MAX) NULL,
	CREATED_AT DATETIME DEFAULT GETDATE(),
    UPDATED_AT DATETIME,
	CONSTRAINT PK_PAYMENTS PRIMARY KEY (ID),
	CONSTRAINT FK_PAYMENTS_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID),
	CONSTRAINT UQ_PAYMENTS_PROVIDER_REF UNIQUE (PROVIDER_REF)
);
GO

CREATE TRIGGER TRG_PAYMENTS_UPDATE_TIMESTAMP
ON PAYMENTS
AFTER UPDATE
AS
BEGIN
	UPDATE P
	SET UPDATED_AT = GETDATE()
	FROM PAYMENTS P
	INNER JOIN INSERTED I ON P.ID = I.ID;
END;
GO

CREATE TABLE RECEIPTS (
	ID INT IDENTITY(1, 1),
	ORDER_ID INT NOT NULL,
	RECEIPT_NUMBER VARCHAR(100) NOT NULL,
	AMOUNT DECIMAL(18, 2) NOT NULL,
	METHOD VARCHAR(50) NOT NULL,
	ISSUED_BY INT NOT NULL,
	ISSUED_AT DATETIME DEFAULT GETDATE(),
	DETAILTS NVARCHAR(MAX) NOT NULL,
	CONSTRAINT PK_RECEIPTS PRIMARY KEY (ID),
	CONSTRAINT FK_RECEIPTS_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID),
	CONSTRAINT FK_RECEIPTS_ISSUED_BY FOREIGN KEY (ISSUED_BY) REFERENCES USERS (ID),
	CONSTRAINT UQ_RECEIPTS_ORDER_ID UNIQUE (ORDER_ID),
	CONSTRAINT UQ_RECEIPTS_RECEIPT_NUMBER UNIQUE (RECEIPT_NUMBER)
);
GO

CREATE TABLE PRINT_JOBS (
	ID INT IDENTITY(1, 1),
	ORDER_ID INT NULL,
	--0 = kitchen_ticket, 1 = receipt, 2 = order_copy
	TYPE TINYINT NOT NULL,
	PAYLOAD NVARCHAR(MAX) NOT NULL,
	PRINTER_ID VARCHAR(100) NOT NULL,
	--0 = queued, 1 = printing, 2 = printed, 3 = failed
	STATUS TINYINT NOT NULL DEFAULT 0,
	ATTEMPTS SMALLINT DEFAULT 0,
	ERROR_MESSAGE NVARCHAR(500) NULL,
	CREATED_AT DATETIME DEFAULT GETDATE(),
	PROCESSED_AT DATETIME NULL,
    UPDATED_AT DATETIME,
	CONSTRAINT PK_PRINT_JOBS PRIMARY KEY (ID),
	CONSTRAINT FK_PRINT_JOBS_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID),
);
GO

CREATE TRIGGER TRG_PRINT_JOBS_UPDATE_TIMESTAMP
ON PRINT_JOBS
AFTER UPDATE
AS
BEGIN
	UPDATE P
	SET UPDATED_AT = GETDATE()
	FROM PRINT_JOBS P
	INNER JOIN INSERTED I ON P.ID = I.ID;
END;
GO

CREATE TABLE AUDIT_LOGS (
	ID BIGINT IDENTITY(1, 1),
	ACTOR_ID INT NULL,
	ACTION VARCHAR(100) NOT NULL,
	ENTITY VARCHAR(50) NOT NULL,
	ENTITY_ID INT NOT NULL,
	OLD_VALUE NVARCHAR(MAX) NULL,
	NEW_VALUE NVARCHAR(MAX) NULL,
	REASON NVARCHAR(500) NULL,
	IP_ADDRESS VARCHAR(45) NULL,
	USER_AGENT NVARCHAR(500) NULL,
	CREATED_AT DATETIME DEFAULT GETDATE(),
	CONSTRAINT PK_AUDIT_LOGS PRIMARY KEY (ID),
	CONSTRAINT FK_AUDIT_LOGS_ACTOR FOREIGN KEY (ACTOR_ID) REFERENCES USERS (ID)
);
GO

--Transitition
CREATE TRIGGER TRG_AUDIT_ORDER_ITEM_STATUS_CHANGE
ON ORDERITEMS
AFTER UPDATE
AS
BEGIN
    -- Chỉ ghi log nếu cột 'status' THỰC SỰ thay đổi
    IF UPDATE(status)
    BEGIN
        INSERT INTO AUDIT_LOGS (
            ACTOR_ID, 
            ACTION, 
            ENTITY, 
            ENTITY_ID, 
            OLD_VALUE, 
            NEW_VALUE, 
            CREATED_AT
        )
        SELECT 
            -- Lấy ID người thực hiện. Cần đặt giá trị này từ ứng dụng vào SESSION_CONTEXT
            CAST(SESSION_CONTEXT(N'current_user_id') AS INT), 
            'order_item_status_changed',
            'OrderItem',
            i.id,
            -- Dùng JSON_QUERY để trích xuất giá trị cũ
            (SELECT status AS old_status FROM deleted FOR JSON PATH, WITHOUT_ARRAY_WRAPPER),
            -- Dùng JSON_QUERY để trích xuất giá trị mới
            (SELECT status AS new_status FROM inserted FOR JSON PATH, WITHOUT_ARRAY_WRAPPER),
            GETDATE()
        FROM inserted i
        INNER JOIN deleted d ON i.id = d.id
        WHERE i.status <> d.status;
    END
END;
GO

CREATE INDEX IX_ORDERS_LIVESTATUS
ON ORDERS (RESTAURANT_ID, STATUS, CREATED_AT DESC);
GO

CREATE INDEX IX_ORDERITEMS_STATUS
ON ORDERITEMS (ORDER_ID, STATUS);
GO

CREATE INDEX IX_MENUITEMS_AVAILABILITY
ON MENUITEMS (RESTAURANT_ID, IS_AVAILABLE);
GO

BACKUP DATABASE QUANLYNHAHANG
TO DISK = N'C:\SQLBackups\RestaurantDB_Full_20251029.bak'
WITH NOINIT, NAME = N'RestaurantDB Full Backup';
GO

BACKUP LOG QUANLYNHAHANG
TO DISK = N'C:\SQLBackups\RestaurantDB_Log_20251029_1000.trn' -- File log thường có đuôi .trn
WITH NOINIT, NAME = N'RestaurantDB Transaction Log Backup';
GO

RESTORE DATABASE QUANLYNHAHANG
FROM DISK = N'C:\SQLBackups\RestaurantDB_Full_20251029.bak' 
WITH FILE = 1,  -- Chỉ số file (thường là 1)
NOUNLOAD, 
STATS = 5; -- Hiển thị tiến trình phục hồi 5% một lần
GO

BACKUP DATABASE QUANLYNHAHANG -- Thay bằng tên Database thực tế
TO DISK = N'C:\SQLBackups\RestaurantDB_Daily.bak'
WITH NOINIT, 
     STATS = 10;
GO

SELECT COUNT(ID) AS PENDING_ORDERS_COUNT FROM ORDERS WHERE STATUS = 0 AND CREATED_AT >= CAST(GETDATE() AS DATE);

SELECT AVG(DATEDIFF(MINUTE, STARTED_AT, FINISHED_AT)) AS AVD_PREPARE_TIME FROM ORDERITEMS WHERE FINISHED_AT IS NOT NULL;

SELECT COUNT(ID) AS FAILED_PRINT_JOBS FROM PRINT_JOBS WHERE STATUS = 3;